// packages/orderbook/src/reasons.ts

/**
 * Defines rejection reasons that can be generated by an OrderBook when processing
 * a request for a specific, known order. The core-engine codes are modeled on the
 * FIX protocol's OrdRejReason (tag 103) values; the 100+ and 9900+ ranges are
 * custom (non-FIX) application codes.
 */
export enum OrderRejectReason {
  // --- Exchange-Level Rejections (Application/Routing Domain, custom codes) ---
  UnknownSymbol = 100,
  MarketClosed = 101,

  // --- OrderBook-Level Rejections (Core Engine / FIX OrdRejReason, tag 103) ---
  UnknownOrder = 5,
  DuplicateOrder = 6, // For future use
  IncorrectQuantity = 13,
  // NONSTANDARD: FIX OrdRejReason 18 is "Invalid price increment"; Invalid
  // Investor ID is 10. Kept at 18 deliberately — the numeric code crosses the
  // process boundary (engine.ts onReject embeds `${code}: ${reason}` into
  // durable ORDER_REJECTED Event-WAL records, which the worker persists to DB
  // audit rows), so renumbering would corrupt the historical audit trail.
  InvalidInvestorID = 18,

  UserContextRequired = 103, // New reason for missing user data

  // --- System/Other Rejections ---
  // Custom codes for non-FIX standard but necessary business rules
  Other = 99,
  InvalidPrice = 9901, // New
  InvalidTickSize = 9902, // New
  OrderAlreadyFilled = 9903,
  QtyLessThanFilled = 9904,
  QtyMustBePositive = 9905,
  NoChange = 9906,
  ConsistencyError = 9907,
  // #586 — engine-level hard share-lock (tier-1 reduce-only). A SELL whose
  // quantity would push the user's aggregate open reduce-only quantity above
  // their owned position (would double-sell locked inventory) is rejected
  // with this code. The stable string is `INSUFFICIENT_AVAILABLE_SHARES`.
  InsufficientAvailableShares = 9908,
}

/**
 * Returns a human-readable string for a given rejection reason code.
 * @param reason The rejection reason code.
 * @returns A descriptive string.
 */

export function getOrderRejectReasonText(reason: OrderRejectReason): string {
  switch (reason) {
    case OrderRejectReason.UnknownSymbol:
      return "Unknown symbol";
    case OrderRejectReason.MarketClosed:
      return "market closed";
    case OrderRejectReason.UnknownOrder:
      return "Unknown order";
    case OrderRejectReason.DuplicateOrder:
      return "Duplicate order";
    case OrderRejectReason.IncorrectQuantity:
      return "Incorrect quantity";
    case OrderRejectReason.InvalidInvestorID:
      return "Unknown User";
    case OrderRejectReason.OrderAlreadyFilled:
      return "Cannot modify a fully filled order";
    case OrderRejectReason.QtyLessThanFilled:
      return "Quantity cannot be less than filled quantity";
    case OrderRejectReason.QtyMustBePositive:
      return "Quantity must be positive; use cancel() to remove order";
    case OrderRejectReason.NoChange:
      return "No changes made in replace request";
    case OrderRejectReason.ConsistencyError:
      return "Order consistency error";
    case OrderRejectReason.InsufficientAvailableShares:
      return "INSUFFICIENT_AVAILABLE_SHARES";
    case OrderRejectReason.UserContextRequired:
      return "User context is missing from the order";
    default:
      return "Other or unknown reason";
  }
}
